# =============================================================================
# Crossplane Kustomization
# =============================================================================
# Agrège tous les fichiers pour déployer Crossplane
# NOTE: Pas de namespace: global car HelmRepository doit être dans flux-system
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - provider-gcp.yaml
  - providerconfig-gcp.yaml

